# Generated by Django 3.0.6 on 2020-05-26 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackademy_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
