# Generated by Django 3.0.6 on 2020-05-26 11:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hackademy_app', '0002_auto_20200526_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lectures',
            fields=[
                ('lecture_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('week', models.CharField(max_length=30)),
                ('url', models.URLField(max_length=300)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackademy_app.Courses')),
            ],
        ),
    ]
