# Generated by Django 3.0.6 on 2020-05-26 12:09

from django.db import migrations, models
import django.db.models.deletion
import hackademy_app.validators


class Migration(migrations.Migration):

    dependencies = [
        ('hackademy_app', '0003_lectures'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackademy_app.Courses')),
                ('lecture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hackademy_app.Lectures')),
            ],
        ),
        migrations.CreateModel(
            name='Solutions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('url', models.URLField(max_length=300, validators=[hackademy_app.validators.validate_url])),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hackademy_app.Tasks')),
            ],
        ),
    ]
